AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Coupon Infomation GET API.
Parameters:
  Env:
    Type: String
    Default: local
  DynamoDBEndpoint:
    Type: String
    Default: https://dynamodb.ap-northeast-1.amazonaws.com/
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/index.getResource
      Runtime: python3.7
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: s3://coupon-api-dev/7a722bb6b72dd8568662ca7412381b43
      Timeout: 30
      Environment:
        Variables:
          ENV:
            Ref: Env
          DYNAMODB_ENDPOINT:
            Ref: DynamoDBEndpoint
          TABLE_NAME:
            Ref: CouponInfoTable
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: GetApi
            Path: /resource/{resourceId}
            Method: get
  TransportTablePutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/transport.putTitle
      Runtime: python3.7
      Policies: AWSLambdaDynamoDBExecutionRole
      CodeUri: s3://coupon-api-dev/7a722bb6b72dd8568662ca7412381b43
      Timeout: 30
      Environment:
        Variables:
          ENV:
            Ref: Env
          DYNAMODB_ENDPOINT:
            Ref: DynamoDBEndpoint
          TABLE_NAME:
            Ref: CouponTitleTable
      Events:
        PutTitle:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::GetAtt:
              - CouponInfoTable
              - StreamArn
            StartingPosition: LATEST
            BatchSize: 1
            Enabled: true
  GetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
  CouponInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: COUPON_INFO
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  CouponTitleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: COUPON_TITLE
      PrimaryKey:
        Name: title_part
        Type: String
