AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Coupon Infomation GET API.
Parameters:
  Env:
    Type: String
    Default: local
  DynamoDBEndpoint:
    Type: String
    Default: https://dynamodb.ap-northeast-1.amazonaws.com/
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/index.getResource
      Runtime: python3.7
      Policies: AmazonDynamoDBReadOnlyAccess
      CodeUri: s3://coupon-api-dev/497edf2f5b1e1f733de204b88fd5b2a5
      Timeout: 30
      Environment:
        Variables:
          ENV:
            Ref: Env
          DYNAMODB_ENDPOINT:
            Ref: DynamoDBEndpoint
          TABLE_NAME:
            Ref: CouponInfoTable
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId:
              Ref: GetApi
            Path: /resource/{resourceId}
            Method: get
  TransportTablePutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/functions/transport.putTitle
      Runtime: python3.7
      Policies: AWSLambdaDynamoDBExecutionRole
      CodeUri: s3://coupon-api-dev/497edf2f5b1e1f733de204b88fd5b2a5
      Timeout: 30
      Environment:
        Variables:
          ENV:
            Ref: Env
          DYNAMODB_ENDPOINT:
            Ref: DynamoDBEndpoint
          TABLE_NAME_TITLE:
            Ref: CouponTitleTable
          TABLE_NAME_INFO:
            Ref: CouponInfoTable
      Events:
        PutTitle:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::GetAtt:
              - CouponInfoTable
              - StreamArn
            StartingPosition: LATEST
            BatchSize: 1
            Enabled: true
      Layers:
      - Ref: TransportLambdaLayer
  GetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      TracingEnabled: true
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
  TransportLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MecabLayer
      Description: Mecab (Morphological analysis) Layer
      ContentUri: s3://coupon-api-dev/d1aee9d5e60f3e57565c85a9d68c64d0
      LicenseInfo: MIT
      RetentionPolicy: Delete
  CouponInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: COUPON_INFO
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  CouponTitleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: COUPON_TITLE
      AttributeDefinitions:
      - AttributeName: title_part
        AttributeType: S
      - AttributeName: coupon_info_id
        AttributeType: S
      KeySchema:
      - AttributeName: title_part
        KeyType: HASH
      - AttributeName: coupon_info_id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
      - IndexName: coupon_info_id_index
        KeySchema:
        - AttributeName: coupon_info_id
          KeyType: HASH
        - AttributeName: title_part
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        Projection:
          ProjectionType: KEYS_ONLY
